### ISSUE TITLE
汇率获取似乎不太对劲？

### ISSUE THREAD

**Issue by qyh214** [EvolvedGhost/Steamhelper#1]
没有详细查看代码，汇率不清楚走的是哪里，好像有点不对，可以考虑接入https://www.exchangerate-api.com/
，然后让大家自己申请api，一般正常调用，是可以免费使用的

**Comment by EvolvedGhost** [comment]
汇率接口为：`https://open.er-api.com/v6/latest/CNY`
接口国内没被墙，可以正常访问
实测和SteamDB差不多的
![image](https://user-images.githubusercontent.com/92856393/199434500-e82b73ca-6461-4ddc-af6e-36ff2603cfc1.png)
![image](https://user-images.githubusercontent.com/92856393/199434547-b65b7379-a74b-4e09-8205-6bcd5c25e77c.png)

请问能不能给点汇率出错的具体情况和例子？

**Comment by qyh214** [comment]
嗯嗯，似乎是我这边的错误得代理到127.0.0.1了，给他放到白名单反而调用比较顺畅了，重启路由器已能正确获取啦……
