### ISSUE TITLE
目前插件的名字匹配似乎有问题

### ISSUE THREAD

**Issue by superexboom** [EvolvedGhost/Steamhelper#2]
使用的是最新版本，早几个月的时候名字匹配还没有太大问题，但是到了最近的两三个月经常出现答非所问的情况，就比如现在dwarf fortress，能搜出来rimworld，不仅是英文名，中文名匹配也有大问题，ID搜索目前到还正常。
还是非常感谢作者制作的插件，非常好用

**Comment by EvolvedGhost** [comment]
你可以尝试下在不登录Steam的情况下用Steam搜索，或者开无痕模式进行搜索，你会发现绝大多数游戏现在默认在Steam的屏蔽列表里，我几个月前已经发现的这个问题（但是有点懒没修）

一个例子：Ground Branch
![image](https://user-images.githubusercontent.com/92856393/213125868-909fa351-cb13-436e-83bf-9db8515046a3.png)
![image](https://user-images.githubusercontent.com/92856393/213125903-96e61cc9-ba36-4454-931c-02db10d6438e.png)

应该过几天能修，暂时先用Steam的APPID吧

**Comment by superexboom** [comment]
确认了下，确实存在这种情况，还挺奇怪的，我还以为是steam改了什么导致api获取不正常了，原来是作妖了，还是非常感谢解答

**Comment by EvolvedGhost** [comment]
v1.0.11 修复

**Comment by superexboom** [comment]
![sh](https://user-images.githubusercontent.com/54000348/213192529-a00d5f08-cfe1-4ded-9076-ce35aec3f756.png)
还有个事情，忘记问了，就是不清楚这个debug的消息是插件的问题，还是我mirai设置有问题，现在群里一条消息，他就会跟一个debug

**Comment by EvolvedGhost** [comment]
> ![sh](https://user-images.githubusercontent.com/54000348/213192529-a00d5f08-cfe1-4ded-9076-ce35aec3f756.png) 还有个事情，忘记问了，就是不清楚这个debug的消息是插件的问题，还是我mirai设置有问题，现在群里一条消息，他就会跟一个debug

我环境是openjdk version "17.0.2" 64位，win server 2019 [1809]，mirai-console 2.13.3 目前没有这个log

你看看你`config\com.evolvedghost.mirai.steamhelper.steamhelper\quartz.properties`下有没有debug相关的设定

我不清楚是不是其他插件启用了一些log类包的依赖，然后开始报DEBUG，如果上面的无效你可以用这个试试，这个在插件配置项设置关闭ERROR级别下的日志，源码在branch 1.0.11-A
[steamhelper-1.0.11-A.mirai2.jar.zip](https://github.com/EvolvedGhost/Steamhelper/files/10447504/steamhelper-1.0.11-A.mirai2.jar.zip)

**Comment by superexboom** [comment]
非常感谢解答，目前似乎没啥问题了，感谢感谢
