### ISSUE TITLE
[Feature] 可以考虑单独把汇率功能分离出来吗？

### ISSUE THREAD

**Issue by NealLemonade** [EvolvedGhost/Steamhelper#3]
emm有的游戏不在steam和epic，这个时候想算汇率但是目前没有找到能支持mirai的相关插件，如果方便的话能麻烦作者增加这一功能吗（不行也没关系）

**Comment by EvolvedGhost** [comment]
插件使用的汇率API并非实时汇率，误差可能有12h以上，因此仅作参考，不建议将任何非实时的汇率API用于正经用途……建议直接百度或者谷歌查汇率，比mirai方便
