### ISSUE TITLE
bug 输入/sh week后没有回应

### ISSUE THREAD

**Issue by Katerina0926** [EvolvedGhost/Steamhelper#4]
![image](https://user-images.githubusercontent.com/104199092/226790717-014cd008-a272-48d3-8f40-e805ada64c2b.png)

**Comment by EvolvedGhost** [comment]
本插件需要 Mirai 官方插件 [chat-command](https://github.com/project-mirai/chat-command)
安装指令：`./mcl --update-package net.mamoe:chat-command --channel stable --type plugin`

**Comment by Katerina0926** [comment]
![image](https://user-images.githubusercontent.com/104199092/226804059-7a2cd305-8156-497a-a082-2d9e3ef89040.png)

**Comment by Katerina0926** [comment]
谢谢

**Comment by Katerina0926** [comment]
docker-compose run --rm mirai
用docker指令启动后 没有反应该怎么解决呢

**Comment by Katerina0926** [comment]
如何在docker命令下启动的mirai 安装chat-command啊
/mcl --update-package net.mamoe:chat-command --channel stable --type plugin吗

**Comment by Katerina0926** [comment]
![image](https://user-images.githubusercontent.com/104199092/226807376-73e73940-85b1-4225-a7b6-50c836d3b3d3.png)
显示存在chat-command 但是还是不回复

**Comment by EvolvedGhost** [comment]
> ![image](https://user-images.githubusercontent.com/104199092/226807376-73e73940-85b1-4225-a7b6-50c836d3b3d3.png) 显示存在chat-command 但是还是不回复

建议再检查下权限节点，此插件的权限节点是Chat Command插件生成的

**Comment by Katerina0926** [comment]
打开后还是未生效 窝放弃了

**Comment by EvolvedGhost** [comment]
长期没有更新ISSUE关闭，仍有问题请再打开
